apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-platform
  namespace: hello-dev
  labels:
    app: hello-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hello-platform

  template:
    metadata:
      labels:
        app: hello-platform

    spec:
      containers:
      - name: hello-platform
        image: ghcr.io/ajezziriglos-bot/hello-platform:cc0427acfe185283b4d9f87e0a030bee125dc6ca
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 8000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10