name: DEV Delivery

on:
  push:
    branches:
      - "feature/github-actions-dev"
    paths-ignore:
      - "k8s/dev/deployment.yaml"

jobs:
  dev-delivery:
    uses: JeddiSoft/platform-workflows/.github/workflows/python-kubernetes-dev.yml@main
    permissions:
      contents: write
      packages: write