name: Prod CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "k8s/prod/deployment.yaml"

jobs:

  promote:
    uses: ajezziriglos-bot/platform-workflows/.github/workflows/kubernetes-promote-prod.yml@main
    permissions:
      contents: write
      packages: read
      